# Change these first
owner: mbootsman # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: toot.re
    url: https://toot.re
    assignees:
      - mbootsman
    
status-website:
  theme: dark
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime monitor for toot.re
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Status page for toot.re - Mastodon instance. No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
