# Change these first
owner: mbootsman # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: toot.re
    url: https://toot.re
    assignees:
      - mbootsman
    
status-website:
  theme: dark
  name: Uptime monitor for toot.re
  cname: status.toot.re
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  
  introTitle: "**Upptime** is monitoring some sites, powered entirely by GitHub."
  introMessage: Status page for toot.re - Mastodon instance. No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/mbootsman/uptime
